# syntax=docker/dockerfile:1

FROM golang:1.23.4 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY *.go ./

RUN CGO_ENABLED=0 GOOS=linux go build -o /go-health-check

#

FROM alpine:latest

WORKDIR /
COPY --from=builder /go-health-check /go-health-check

EXPOSE 80

USER nonroot:nonroot

CMD ["/go-health-check"]